#!/bin/sh
set -e

case "$1" in
    start)
        echo "loading scull faulty hello"
        scull_load
        module_load faulty
        modprobe hello
        aesdchar_load
    ;;
    stop)
        echo "unloading scull faulty hello"
        scull_unload
        module_unload faulty
        modprobe -r hello
        aesdchar_unload
    ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit 0
